/*
 * Copyright (c) 2010 The Jackson Laboratory
 * 
 * This is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This software is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this software.  If not, see <http://www.gnu.org/licenses/>.
 */

package org.jax.util.project.gui;

import javax.swing.JOptionPane;

import org.jax.util.TextWrapper;
import org.jax.util.project.Project;
import org.jax.util.project.ProjectManager;

/**
 * A dialog for creating or renaming a project
 * @author <A HREF="mailto:keith.sheppard@jax.org">Keith Sheppard</A>
 */
public class CreateOrRenameProjectDialog extends javax.swing.JDialog
{
    /**
     * every {@link java.io.Serializable} is supposed to have one of these
     */
    private static final long serialVersionUID = -9212535713990794406L;
    
    /**
     * for distinguishing between creating a new project or renaming
     * an existing project
     */
    public static enum DialogMode
    {
        /**
         * for creating a new project
         */
        CREATE,
        
        /**
         * for renaming an existing project
         */
        RENAME
    }
    
    private final DialogMode mode;
    private final ProjectManager projectManager;
    private final Project project;
    
    /**
     * Constructor for rename
     * @param parent
     *          the parent frame
     * @param projectManager
     *          the project manager
     * @param project
     *          the project
     */
    public CreateOrRenameProjectDialog(
            java.awt.Frame parent,
            ProjectManager projectManager,
            Project project)
    {
        this(parent, DialogMode.RENAME, projectManager, project);
    }
    
    /**
     * Constructor for create
     * @param parent
     *          the parent frame
     * @param projectManager
     *          the project manager
     */
    public CreateOrRenameProjectDialog(
            java.awt.Frame parent,
            ProjectManager projectManager)
    {
        this(parent, DialogMode.CREATE, projectManager, null);
    }
    
    /**
     * Constructor
     * @param parent
     *          the parent frame
     * @param mode
     *          the mode that determines whether we're creating a project
     *          or renaming an existing project
     * @param projectManager
     *          the project manager
     * @param project
     *          the project
     */
    private CreateOrRenameProjectDialog(
            java.awt.Frame parent,
            DialogMode mode,
            ProjectManager projectManager,
            Project project)
    {
        super(parent, true);
        
        this.projectManager = projectManager;
        this.project = project;
        
        this.mode = mode;
        this.initComponents();
        if(mode == DialogMode.RENAME)
        {
            String currProjectName = this.project.getName();
            if(currProjectName == null)
            {
                currProjectName = "";
            }
            
            this.setTitle("Rename Project");
            this.projectNameTextField.setText(currProjectName);
            this.projectNameTextField.setSelectionStart(0);
            this.projectNameTextField.setSelectionEnd(currProjectName.length());
        }
        else
        {
            this.setTitle("Create Project");
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("all")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        projectNameLabel = new javax.swing.JLabel();
        projectNameTextField = new javax.swing.JTextField();
        actionPanel = new javax.swing.JPanel();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        projectNameLabel.setText("Project Name:");

        projectNameTextField.setFocusCycleRoot(true);

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });
        actionPanel.add(okButton);

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        actionPanel.add(cancelButton);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(projectNameLabel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(projectNameTextField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                .addContainerGap())
            .add(actionPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(projectNameLabel)
                    .add(projectNameTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(actionPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        String projectName = this.projectNameTextField.getText().trim();
        if(projectName.length() == 0)
        {
            String message =
                "Project name cannot be empty. Please enter a project name or " +
                "cancel.";
            JOptionPane.showMessageDialog(
                    this,
                    TextWrapper.wrapText(
                            message,
                            TextWrapper.DEFAULT_DIALOG_COLUMN_COUNT),
                    "Empty Project Name",
                    JOptionPane.WARNING_MESSAGE);
        }
        else
        {
            if(this.mode == DialogMode.CREATE)
            {
                this.projectManager.createNewActiveProject().setName(projectName);
            }
            else
            {
                this.project.setName(projectName);
            }
            this.dispose();
        }
    }//GEN-LAST:event_okButtonActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel actionPanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton okButton;
    private javax.swing.JLabel projectNameLabel;
    private javax.swing.JTextField projectNameTextField;
    // End of variables declaration//GEN-END:variables
    
}
